name: go_absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: 3.3.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.4.1
  firebase_core: 1.19.2
  firebase_storage: 10.3.2
  flutter:
    sdk: flutter
  get: 4.6.5
  lottie: ^1.3.0

dev_dependencies:
  change_app_package_name: 1.1.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
  uses-material-design: true
