name: go_absensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  firebase_storage: 10.2.17
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

